# general settings
name: MAT_x2_from_scratch
model_type: SRModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    # dataroot_gt: datasets/DF2K/DF2K_train_HR_sub
    # dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic/X2_sub
    # meta_info_file: basicsr/data/meta_info/meta_info_DF2K3450sub_GT.txt
    # (for lmdb)
    dataroot_gt: datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic_X2_sub.lmdb

    io_backend:
      # type: disk
      # (for lmdb)
      type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmod2
    dataroot_lq: datasets/Set5/LRbicx2
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/GTmod2
    dataroot_lq: datasets/Set14/LRbicx2
    io_backend:
      type: disk

  val_3:
    name: BSD100
    type: PairedImageDataset
    dataroot_gt: datasets/BSD100/GTmod2
    dataroot_lq: datasets/BSD100/LRbicx2
    io_backend:
      type: disk

  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/Urban100/GTmod2
    dataroot_lq: datasets/Urban100/LRbicx2
    io_backend:
      type: disk

# network structures
network_g:
  type: MAT
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 156
  num_block: 6
  expanded_ratio: 2
  squeeze_factor: 2
  depth: 6
  num_head: 6
  kernel_sizes: [13, 15, 17]
  dilations: [[1, 1, 1], [4, 4, 3]]
  rel_pos_bias: true
  dw_sizes: [1, 3, 5, 7]
  upscale: 2
  upsampler: 'pixelshuffle'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500